services:
  reminder:
    build: .
    container_name: narfu-reminder
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - path: .env
        required: false
    environment:
      - TZ=Europe/Moscow
